# Generated by Django 5.0.8 on 2024-08-11 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartyJoinInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('message', models.CharField(blank=True, max_length=255, verbose_name='invitation message')),
            ],
            options={
                'db_table': 'parties_join_invitations',
            },
        ),
        migrations.CreateModel(
            name='PartyJoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('message', models.CharField(blank=True, max_length=255, verbose_name='Party join request message')),
            ],
            options={
                'db_table': 'parties_join_requests',
            },
        ),
        migrations.CreateModel(
            name='PartyMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField(default=False, help_text="Party admins can update the party's data and manage its members.", verbose_name='party admin')),
            ],
            options={
                'db_table': 'parties_memberships',
            },
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, verbose_name='party name')),
                ('slug_name', models.SlugField(max_length=40, unique=True)),
                ('about', models.CharField(max_length=255, verbose_name='party description')),
                ('picture', models.CharField(max_length=255, verbose_name='party image')),
                ('max_members', models.IntegerField(default=50, verbose_name='party max members')),
                ('is_public', models.BooleanField(default=True, help_text='Public parties are listed in the main page so everyone know about their existence.')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.tournament')),
            ],
            options={
                'db_table': 'parties',
            },
        ),
    ]
