# Generated by Django 5.0.8 on 2024-08-08 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='partyjoininvitation',
            name='issued_by',
            field=models.ForeignKey(help_text='Party member that is providing the invitation', on_delete=django.db.models.deletion.CASCADE, related_name='issued_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='partyjoininvitation',
            name='issued_to',
            field=models.ForeignKey(help_text='User that has been invited to the party', on_delete=django.db.models.deletion.CASCADE, related_name='issued_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='partyjoininvitation',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parties.party'),
        ),
        migrations.AddField(
            model_name='partyjoinrequest',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parties.party'),
        ),
        migrations.AddField(
            model_name='partyjoinrequest',
            name='requested_by',
            field=models.ForeignKey(help_text='User that is requesting to join', on_delete=django.db.models.deletion.CASCADE, related_name='requested_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='partymembership',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parties.party'),
        ),
        migrations.AddField(
            model_name='partymembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='party',
            name='members',
            field=models.ManyToManyField(through='parties.PartyMembership', to=settings.AUTH_USER_MODEL),
        ),
    ]
