# Generated by Django 5.0.8 on 2024-08-09 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='members',
            field=models.ManyToManyField(related_name='party_memberships', through='parties.PartyMembership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='partymembership',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='parties.party'),
        ),
        migrations.AlterField(
            model_name='partymembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL),
        ),
    ]
