# Generated by Django 5.0.8 on 2024-08-09 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournament',
            old_name='isFinished',
            new_name='is_finished',
        ),
    ]
